// ignore_for_file: equal_keys_in_map

import 'package:get/get.dart';

class MyTranslation implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          'app_name': 'التجربه',
          'user': 'المستخدمين',
          'property': 'عقارات',
          'booking': 'الحجز',
          'setting': 'الإعدادت',
          'name :': 'الاسم :',
          'email :': 'البريد الالكتروني :',
          'phone :': 'رقم الجوال :',
          'role :': 'الملكيه :',
          'intro': 'الفديو التعريفي',
          'edit': 'تحديث الملف الشخصي',
          'location :': 'الموقع :',
          'price :': 'السعر :',
          'price': 'السعر',
          'owner :': 'المالك :',
          'start_date': 'تاريخ البدء :',
          'end_date': 'تاريخ الانتهاء :',
          'lang': 'تغيير اللغه',
          'change': 'تغيير',
          'theme': 'الثيمات',
          'bodytheme1': 'تغيير الثيمات التطبيق',
          'bodytheme2':
              'لا بد من اختيار اي الثيمات التي تفضل ان يكون بيها الجهاز اي من الاختيارات تفضل ؟؟ ',
          'darkmode': 'الوضع المظلم',
          'lightmode': 'الوضه الفاتح',
          'cond': 'بذالك تتم الموافقه علي ',
          'termuse': 'شروط الاستخدام',
          'privacypolicy': 'سياسة الخصوصية',
          'and': ' و ',
          'role': 'الملكيه',
          'create_user': 'مستخدم جديد',
          'create_property': 'عقار جديد',
          'create_booking': 'حجز جديد',
          'create_setting': 'اعدادات جديدة',
          'property_name': 'اسم العقار',
          'des_property': 'وصف العقار',
          'location_property': 'موقع العقار',
          'owner_name': 'اسم المالك',
          'delete': 'حذف',
          'start_date': 'تاريخ البدء',
          'enddata': 'تاريخ الانتهاء',
          'stauts': 'الحاله',
          'editbooking': 'تعديل الحجز',
          'editproperty': 'تعديل العقار',
          'photo': 'الصور',
          'camera': 'تصوير',
          'gallary': 'المعرض',
          'photo1': 'اختيار الصوره',
          'photo2':
              'يجب عليك اختيار اي طريقه لتمكن من اختيار صورتك عن طريق الص،ر او المعرض',
        },
        "en": {
          'app_name': 'Test 1',
          'user': 'Users',
          'property': 'Property',
          'booking': 'Booking',
          'setting': 'Setting',
          'name :': 'Name :',
          'email :': 'Email :',
          'phone :': 'Phone :',
          'role :': 'Role :',
          'role': 'Role',
          'intro': 'Intro Video',
          'edit': 'Edit Profile',
          'location :': 'Location :',
          'price :': 'Price :',
          'price': 'Price',
          'owner :': 'Owner :',
          'startdate': 'Start Date :',
          'start_date': 'Start Date',
          'enddata': 'End Date',
          'end_date': 'End Date :',
          'lang': 'Change Language',
          'change': 'Change',
          'theme': 'Theme',
          'bodytheme1': 'Change Theme Mode',
          'bodytheme2':
              'You must choose which themes you would like the device to have. Which of the options do you prefer ??',
          'darkmode': 'Darks Mode',
          'lightmode': 'Light Mode',
          'cond': 'Confirm of ',
          'termuse': 'Terms Of Use',
          'privacypolicy': 'Privacy Policy',
          'and': ' and ',
          'create_user': 'New User',
          'create_property': 'New Property',
          'create_booking': 'New Booking',
          'create_setting': 'New Setting',
          'property_name': 'Property Name',
          'des_property': 'Property Description',
          'location_property': 'Property Location',
          'owner_name': 'Owner Name',
          'delete': 'Delete',
          'stauts': 'Status',
          'editbooking': 'Edit Booking',
          'editproperty': 'Edit Property',
          'photo': 'Photos',
          'camera': 'Camera',
          'gallary': 'Gallary',
          'photo1': 'Pick Photo',
          'photo2':
              'You have to choice which way do you want to upload your photo by camera or gallrey',
        },
      };
}
